spring:
  application:
    name: Job Board
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: password
  jpa:
    show-sql: true
    defer-datasource-initialization: true